server:
  port:
    18560
# 应用名称
spring:
  application:
    name: xydmall-externalservice
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.184.134:8848
alibaba:
  cloud:
    access-key: LTAI4GEtzdfbStuim7N8EX1m
    secret-key: CDlYCDMxHgchcPxRqWJN90GV0cfdNz
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      bucket: xydmall-oss
      host: https://${alibaba.cloud.oss.bucket}.${alibaba.cloud.oss.endpoint}


